//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{
    public static class ConnectionHelper
    {
        static Type[] persistentTypes = new Type[] {
            typeof(gen_table),
            typeof(gen_table_column),
            typeof(QRTZ_BLOB_TRIGGERS),
            typeof(QRTZ_CALENDARS),
            typeof(QRTZ_CRON_TRIGGERS),
            typeof(QRTZ_FIRED_TRIGGERS),
            typeof(QRTZ_JOB_DETAILS),
            typeof(QRTZ_LOCKS),
            typeof(QRTZ_PAUSED_TRIGGER_GRPS),
            typeof(QRTZ_SCHEDULER_STATE),
            typeof(QRTZ_SIMPLE_TRIGGERS),
            typeof(QRTZ_SIMPROP_TRIGGERS),
            typeof(QRTZ_TRIGGERS),
            typeof(sys_config),
            typeof(sys_dept),
            typeof(sys_dict_data),
            typeof(sys_dict_type),
            typeof(sys_job),
            typeof(sys_job_log),
            typeof(sys_logininfor),
            typeof(sys_menu),
            typeof(sys_notice),
            typeof(sys_oper_log),
            typeof(sys_post),
            typeof(sys_project),
            typeof(sys_role),
            typeof(sys_role_dept),
            typeof(sys_role_menu),
            typeof(sys_user),
            typeof(sys_user_online),
            typeof(sys_user_post),
            typeof(sys_user_role),
            typeof(Usertt)
        };
        public static Type[] GetPersistentTypes()
        {
            Type[] copy = new Type[persistentTypes.Length];
            Array.Copy(persistentTypes, copy, persistentTypes.Length);
            return copy;
        }
        public static string ConnectionString { get { return System.Configuration.ConfigurationManager.ConnectionStrings["www.y8848.cnruoyi"].ConnectionString; } }
        public static void Connect(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, bool threadSafe = false)
        {
            if (threadSafe)
            {
                var provider = XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
                var dictionary = new DevExpress.Xpo.Metadata.ReflectionDictionary();
                dictionary.GetDataStoreSchema(persistentTypes);
                XpoDefault.DataLayer = new ThreadSafeDataLayer(dictionary, provider);
            }
            else
            {
                XpoDefault.DataLayer = XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
            }
            XpoDefault.Session = null;
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, out IDisposable[] objectsToDisposeOnDisconnect)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption, out objectsToDisposeOnDisconnect);
        }
        public static IDataLayer GetDataLayer(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
        }
    }

}
