//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class gen_table_column : XPLiteObject
    {
        long fcolumn_id;
        [Key(true)]
        public long column_id
        {
            get { return fcolumn_id; }
            set { SetPropertyValue<long>(nameof(column_id), ref fcolumn_id, value); }
        }
        string ftable_id;
        [Size(64)]
        public string table_id
        {
            get { return ftable_id; }
            set { SetPropertyValue<string>(nameof(table_id), ref ftable_id, value); }
        }
        string fcolumn_name;
        [Size(200)]
        public string column_name
        {
            get { return fcolumn_name; }
            set { SetPropertyValue<string>(nameof(column_name), ref fcolumn_name, value); }
        }
        string fcolumn_comment;
        [Size(500)]
        public string column_comment
        {
            get { return fcolumn_comment; }
            set { SetPropertyValue<string>(nameof(column_comment), ref fcolumn_comment, value); }
        }
        string fcolumn_type;
        public string column_type
        {
            get { return fcolumn_type; }
            set { SetPropertyValue<string>(nameof(column_type), ref fcolumn_type, value); }
        }
        string fjava_type;
        [Size(500)]
        public string java_type
        {
            get { return fjava_type; }
            set { SetPropertyValue<string>(nameof(java_type), ref fjava_type, value); }
        }
        string fjava_field;
        [Size(200)]
        public string java_field
        {
            get { return fjava_field; }
            set { SetPropertyValue<string>(nameof(java_field), ref fjava_field, value); }
        }
        char fis_pk;
        public char is_pk
        {
            get { return fis_pk; }
            set { SetPropertyValue<char>(nameof(is_pk), ref fis_pk, value); }
        }
        char fis_increment;
        public char is_increment
        {
            get { return fis_increment; }
            set { SetPropertyValue<char>(nameof(is_increment), ref fis_increment, value); }
        }
        char fis_required;
        public char is_required
        {
            get { return fis_required; }
            set { SetPropertyValue<char>(nameof(is_required), ref fis_required, value); }
        }
        char fis_insert;
        public char is_insert
        {
            get { return fis_insert; }
            set { SetPropertyValue<char>(nameof(is_insert), ref fis_insert, value); }
        }
        char fis_edit;
        public char is_edit
        {
            get { return fis_edit; }
            set { SetPropertyValue<char>(nameof(is_edit), ref fis_edit, value); }
        }
        char fis_list;
        public char is_list
        {
            get { return fis_list; }
            set { SetPropertyValue<char>(nameof(is_list), ref fis_list, value); }
        }
        char fis_query;
        public char is_query
        {
            get { return fis_query; }
            set { SetPropertyValue<char>(nameof(is_query), ref fis_query, value); }
        }
        string fquery_type;
        [Size(200)]
        [ColumnDefaultValue("EQ")]
        public string query_type
        {
            get { return fquery_type; }
            set { SetPropertyValue<string>(nameof(query_type), ref fquery_type, value); }
        }
        string fhtml_type;
        [Size(200)]
        public string html_type
        {
            get { return fhtml_type; }
            set { SetPropertyValue<string>(nameof(html_type), ref fhtml_type, value); }
        }
        string fdict_type;
        [Size(200)]
        [ColumnDefaultValue("")]
        public string dict_type
        {
            get { return fdict_type; }
            set { SetPropertyValue<string>(nameof(dict_type), ref fdict_type, value); }
        }
        int fsort;
        public int sort
        {
            get { return fsort; }
            set { SetPropertyValue<int>(nameof(sort), ref fsort, value); }
        }
        string fcreate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string create_by
        {
            get { return fcreate_by; }
            set { SetPropertyValue<string>(nameof(create_by), ref fcreate_by, value); }
        }
        DateTime fcreate_time;
        public DateTime create_time
        {
            get { return fcreate_time; }
            set { SetPropertyValue<DateTime>(nameof(create_time), ref fcreate_time, value); }
        }
        string fupdate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string update_by
        {
            get { return fupdate_by; }
            set { SetPropertyValue<string>(nameof(update_by), ref fupdate_by, value); }
        }
        DateTime fupdate_time;
        public DateTime update_time
        {
            get { return fupdate_time; }
            set { SetPropertyValue<DateTime>(nameof(update_time), ref fupdate_time, value); }
        }
    }

}
