//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class QRTZ_SCHEDULER_STATE : XPLiteObject
    {
        long flast_checkin_time;
        public long last_checkin_time
        {
            get { return flast_checkin_time; }
            set { SetPropertyValue<long>(nameof(last_checkin_time), ref flast_checkin_time, value); }
        }
        long fcheckin_interval;
        public long checkin_interval
        {
            get { return fcheckin_interval; }
            set { SetPropertyValue<long>(nameof(checkin_interval), ref fcheckin_interval, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(120)]
            [Persistent("sched_name")]
            public string sched_name { get; set; }
            [Size(200)]
            [Persistent("instance_name")]
            public string instance_name { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
