//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class QRTZ_TRIGGERS : XPLiteObject
    {
        string fjob_name;
        [Size(200)]
        public string job_name
        {
            get { return fjob_name; }
            set { SetPropertyValue<string>(nameof(job_name), ref fjob_name, value); }
        }
        string fjob_group;
        [Size(200)]
        public string job_group
        {
            get { return fjob_group; }
            set { SetPropertyValue<string>(nameof(job_group), ref fjob_group, value); }
        }
        string fdescription;
        [Size(250)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>(nameof(description), ref fdescription, value); }
        }
        long fnext_fire_time;
        public long next_fire_time
        {
            get { return fnext_fire_time; }
            set { SetPropertyValue<long>(nameof(next_fire_time), ref fnext_fire_time, value); }
        }
        long fprev_fire_time;
        public long prev_fire_time
        {
            get { return fprev_fire_time; }
            set { SetPropertyValue<long>(nameof(prev_fire_time), ref fprev_fire_time, value); }
        }
        int fpriority;
        public int priority
        {
            get { return fpriority; }
            set { SetPropertyValue<int>(nameof(priority), ref fpriority, value); }
        }
        string ftrigger_state;
        [Size(16)]
        public string trigger_state
        {
            get { return ftrigger_state; }
            set { SetPropertyValue<string>(nameof(trigger_state), ref ftrigger_state, value); }
        }
        string ftrigger_type;
        [Size(8)]
        public string trigger_type
        {
            get { return ftrigger_type; }
            set { SetPropertyValue<string>(nameof(trigger_type), ref ftrigger_type, value); }
        }
        long fstart_time;
        public long start_time
        {
            get { return fstart_time; }
            set { SetPropertyValue<long>(nameof(start_time), ref fstart_time, value); }
        }
        long fend_time;
        public long end_time
        {
            get { return fend_time; }
            set { SetPropertyValue<long>(nameof(end_time), ref fend_time, value); }
        }
        string fcalendar_name;
        [Size(200)]
        public string calendar_name
        {
            get { return fcalendar_name; }
            set { SetPropertyValue<string>(nameof(calendar_name), ref fcalendar_name, value); }
        }
        short fmisfire_instr;
        public short misfire_instr
        {
            get { return fmisfire_instr; }
            set { SetPropertyValue<short>(nameof(misfire_instr), ref fmisfire_instr, value); }
        }
        byte[] fjob_data;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] job_data
        {
            get { return fjob_data; }
            set { SetPropertyValue<byte[]>(nameof(job_data), ref fjob_data, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(120)]
            [Persistent("sched_name")]
            public string sched_name { get; set; }
            [Size(200)]
            [Persistent("trigger_name")]
            public string trigger_name { get; set; }
            [Size(200)]
            [Persistent("trigger_group")]
            public string trigger_group { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
