//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class QRTZ_JOB_DETAILS : XPLiteObject
    {
        string fdescription;
        [Size(250)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>(nameof(description), ref fdescription, value); }
        }
        string fjob_class_name;
        [Size(250)]
        public string job_class_name
        {
            get { return fjob_class_name; }
            set { SetPropertyValue<string>(nameof(job_class_name), ref fjob_class_name, value); }
        }
        string fis_durable;
        [Size(1)]
        public string is_durable
        {
            get { return fis_durable; }
            set { SetPropertyValue<string>(nameof(is_durable), ref fis_durable, value); }
        }
        string fis_nonconcurrent;
        [Size(1)]
        public string is_nonconcurrent
        {
            get { return fis_nonconcurrent; }
            set { SetPropertyValue<string>(nameof(is_nonconcurrent), ref fis_nonconcurrent, value); }
        }
        string fis_update_data;
        [Size(1)]
        public string is_update_data
        {
            get { return fis_update_data; }
            set { SetPropertyValue<string>(nameof(is_update_data), ref fis_update_data, value); }
        }
        string frequests_recovery;
        [Size(1)]
        public string requests_recovery
        {
            get { return frequests_recovery; }
            set { SetPropertyValue<string>(nameof(requests_recovery), ref frequests_recovery, value); }
        }
        byte[] fjob_data;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] job_data
        {
            get { return fjob_data; }
            set { SetPropertyValue<byte[]>(nameof(job_data), ref fjob_data, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(120)]
            [Persistent("sched_name")]
            public string sched_name { get; set; }
            [Size(200)]
            [Persistent("job_name")]
            public string job_name { get; set; }
            [Size(200)]
            [Persistent("job_group")]
            public string job_group { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
