//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class QRTZ_CRON_TRIGGERS : XPLiteObject
    {
        string fcron_expression;
        [Size(200)]
        public string cron_expression
        {
            get { return fcron_expression; }
            set { SetPropertyValue<string>(nameof(cron_expression), ref fcron_expression, value); }
        }
        string ftime_zone_id;
        [Size(80)]
        public string time_zone_id
        {
            get { return ftime_zone_id; }
            set { SetPropertyValue<string>(nameof(time_zone_id), ref ftime_zone_id, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(120)]
            [Persistent("sched_name")]
            public string sched_name { get; set; }
            [Size(200)]
            [Persistent("trigger_name")]
            public string trigger_name { get; set; }
            [Size(200)]
            [Persistent("trigger_group")]
            public string trigger_group { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
