//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class QRTZ_SIMPLE_TRIGGERS : XPLiteObject
    {
        long frepeat_count;
        public long repeat_count
        {
            get { return frepeat_count; }
            set { SetPropertyValue<long>(nameof(repeat_count), ref frepeat_count, value); }
        }
        long frepeat_interval;
        public long repeat_interval
        {
            get { return frepeat_interval; }
            set { SetPropertyValue<long>(nameof(repeat_interval), ref frepeat_interval, value); }
        }
        long ftimes_triggered;
        public long times_triggered
        {
            get { return ftimes_triggered; }
            set { SetPropertyValue<long>(nameof(times_triggered), ref ftimes_triggered, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(120)]
            [Persistent("sched_name")]
            public string sched_name { get; set; }
            [Size(200)]
            [Persistent("trigger_name")]
            public string trigger_name { get; set; }
            [Size(200)]
            [Persistent("trigger_group")]
            public string trigger_group { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
