//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class QRTZ_FIRED_TRIGGERS : XPLiteObject
    {
        string ftrigger_name;
        [Size(200)]
        public string trigger_name
        {
            get { return ftrigger_name; }
            set { SetPropertyValue<string>(nameof(trigger_name), ref ftrigger_name, value); }
        }
        string ftrigger_group;
        [Size(200)]
        public string trigger_group
        {
            get { return ftrigger_group; }
            set { SetPropertyValue<string>(nameof(trigger_group), ref ftrigger_group, value); }
        }
        string finstance_name;
        [Size(200)]
        public string instance_name
        {
            get { return finstance_name; }
            set { SetPropertyValue<string>(nameof(instance_name), ref finstance_name, value); }
        }
        long ffired_time;
        public long fired_time
        {
            get { return ffired_time; }
            set { SetPropertyValue<long>(nameof(fired_time), ref ffired_time, value); }
        }
        long fsched_time;
        public long sched_time
        {
            get { return fsched_time; }
            set { SetPropertyValue<long>(nameof(sched_time), ref fsched_time, value); }
        }
        int fpriority;
        public int priority
        {
            get { return fpriority; }
            set { SetPropertyValue<int>(nameof(priority), ref fpriority, value); }
        }
        string fstate;
        [Size(16)]
        public string state
        {
            get { return fstate; }
            set { SetPropertyValue<string>(nameof(state), ref fstate, value); }
        }
        string fjob_name;
        [Size(200)]
        public string job_name
        {
            get { return fjob_name; }
            set { SetPropertyValue<string>(nameof(job_name), ref fjob_name, value); }
        }
        string fjob_group;
        [Size(200)]
        public string job_group
        {
            get { return fjob_group; }
            set { SetPropertyValue<string>(nameof(job_group), ref fjob_group, value); }
        }
        string fis_nonconcurrent;
        [Size(1)]
        public string is_nonconcurrent
        {
            get { return fis_nonconcurrent; }
            set { SetPropertyValue<string>(nameof(is_nonconcurrent), ref fis_nonconcurrent, value); }
        }
        string frequests_recovery;
        [Size(1)]
        public string requests_recovery
        {
            get { return frequests_recovery; }
            set { SetPropertyValue<string>(nameof(requests_recovery), ref frequests_recovery, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(120)]
            [Persistent("sched_name")]
            public string sched_name { get; set; }
            [Size(95)]
            [Persistent("entry_id")]
            public string entry_id { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
