//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class sys_config : XPLiteObject
    {
        int fconfig_id;
        [Key(true)]
        public int config_id
        {
            get { return fconfig_id; }
            set { SetPropertyValue<int>(nameof(config_id), ref fconfig_id, value); }
        }
        string fconfig_name;
        [ColumnDefaultValue("")]
        public string config_name
        {
            get { return fconfig_name; }
            set { SetPropertyValue<string>(nameof(config_name), ref fconfig_name, value); }
        }
        string fconfig_key;
        [ColumnDefaultValue("")]
        public string config_key
        {
            get { return fconfig_key; }
            set { SetPropertyValue<string>(nameof(config_key), ref fconfig_key, value); }
        }
        string fconfig_value;
        [Size(500)]
        [ColumnDefaultValue("")]
        public string config_value
        {
            get { return fconfig_value; }
            set { SetPropertyValue<string>(nameof(config_value), ref fconfig_value, value); }
        }
        char fconfig_type;
        [ColumnDefaultValue('N')]
        public char config_type
        {
            get { return fconfig_type; }
            set { SetPropertyValue<char>(nameof(config_type), ref fconfig_type, value); }
        }
        string fcreate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string create_by
        {
            get { return fcreate_by; }
            set { SetPropertyValue<string>(nameof(create_by), ref fcreate_by, value); }
        }
        DateTime fcreate_time;
        public DateTime create_time
        {
            get { return fcreate_time; }
            set { SetPropertyValue<DateTime>(nameof(create_time), ref fcreate_time, value); }
        }
        string fupdate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string update_by
        {
            get { return fupdate_by; }
            set { SetPropertyValue<string>(nameof(update_by), ref fupdate_by, value); }
        }
        DateTime fupdate_time;
        public DateTime update_time
        {
            get { return fupdate_time; }
            set { SetPropertyValue<DateTime>(nameof(update_time), ref fupdate_time, value); }
        }
        string fremark;
        [Size(500)]
        public string remark
        {
            get { return fremark; }
            set { SetPropertyValue<string>(nameof(remark), ref fremark, value); }
        }
    }

}
