//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class sys_user_online : XPLiteObject
    {
        string fsessionId;
        [Key]
        [Size(50)]
        public string sessionId
        {
            get { return fsessionId; }
            set { SetPropertyValue<string>(nameof(sessionId), ref fsessionId, value); }
        }
        string flogin_name;
        [Size(50)]
        [ColumnDefaultValue("")]
        public string login_name
        {
            get { return flogin_name; }
            set { SetPropertyValue<string>(nameof(login_name), ref flogin_name, value); }
        }
        string fdept_name;
        [Size(50)]
        [ColumnDefaultValue("")]
        public string dept_name
        {
            get { return fdept_name; }
            set { SetPropertyValue<string>(nameof(dept_name), ref fdept_name, value); }
        }
        string fipaddr;
        [Size(50)]
        [ColumnDefaultValue("")]
        public string ipaddr
        {
            get { return fipaddr; }
            set { SetPropertyValue<string>(nameof(ipaddr), ref fipaddr, value); }
        }
        string flogin_location;
        [Size(255)]
        [ColumnDefaultValue("")]
        public string login_location
        {
            get { return flogin_location; }
            set { SetPropertyValue<string>(nameof(login_location), ref flogin_location, value); }
        }
        string fbrowser;
        [Size(50)]
        [ColumnDefaultValue("")]
        public string browser
        {
            get { return fbrowser; }
            set { SetPropertyValue<string>(nameof(browser), ref fbrowser, value); }
        }
        string fos;
        [Size(50)]
        [ColumnDefaultValue("")]
        public string os
        {
            get { return fos; }
            set { SetPropertyValue<string>(nameof(os), ref fos, value); }
        }
        string fstatus;
        [Size(10)]
        [ColumnDefaultValue("")]
        public string status
        {
            get { return fstatus; }
            set { SetPropertyValue<string>(nameof(status), ref fstatus, value); }
        }
        DateTime fstart_timestamp;
        public DateTime start_timestamp
        {
            get { return fstart_timestamp; }
            set { SetPropertyValue<DateTime>(nameof(start_timestamp), ref fstart_timestamp, value); }
        }
        DateTime flast_access_time;
        public DateTime last_access_time
        {
            get { return flast_access_time; }
            set { SetPropertyValue<DateTime>(nameof(last_access_time), ref flast_access_time, value); }
        }
        int fexpire_time;
        [ColumnDefaultValue(0)]
        public int expire_time
        {
            get { return fexpire_time; }
            set { SetPropertyValue<int>(nameof(expire_time), ref fexpire_time, value); }
        }
    }

}
