//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class sys_user : XPLiteObject
    {
        long fuser_id;
        [Key(true)]
        public long user_id
        {
            get { return fuser_id; }
            set { SetPropertyValue<long>(nameof(user_id), ref fuser_id, value); }
        }
        long fdept_id;
        public long dept_id
        {
            get { return fdept_id; }
            set { SetPropertyValue<long>(nameof(dept_id), ref fdept_id, value); }
        }
        string flogin_name;
        [Size(30)]
        public string login_name
        {
            get { return flogin_name; }
            set { SetPropertyValue<string>(nameof(login_name), ref flogin_name, value); }
        }
        string fuser_name;
        [Size(30)]
        [ColumnDefaultValue("")]
        public string user_name
        {
            get { return fuser_name; }
            set { SetPropertyValue<string>(nameof(user_name), ref fuser_name, value); }
        }
        string fuser_type;
        [Size(2)]
        [ColumnDefaultValue("00")]
        public string user_type
        {
            get { return fuser_type; }
            set { SetPropertyValue<string>(nameof(user_type), ref fuser_type, value); }
        }
        string femail;
        [Size(50)]
        [ColumnDefaultValue("")]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        string fphonenumber;
        [Size(11)]
        [ColumnDefaultValue("")]
        public string phonenumber
        {
            get { return fphonenumber; }
            set { SetPropertyValue<string>(nameof(phonenumber), ref fphonenumber, value); }
        }
        char fsex;
        [ColumnDefaultValue('0')]
        public char sex
        {
            get { return fsex; }
            set { SetPropertyValue<char>(nameof(sex), ref fsex, value); }
        }
        string favatar;
        [ColumnDefaultValue("")]
        public string avatar
        {
            get { return favatar; }
            set { SetPropertyValue<string>(nameof(avatar), ref favatar, value); }
        }
        string fpassword;
        [Size(50)]
        [ColumnDefaultValue("")]
        public string password
        {
            get { return fpassword; }
            set { SetPropertyValue<string>(nameof(password), ref fpassword, value); }
        }
        string fsalt;
        [Size(20)]
        [ColumnDefaultValue("")]
        public string salt
        {
            get { return fsalt; }
            set { SetPropertyValue<string>(nameof(salt), ref fsalt, value); }
        }
        char fstatus;
        [ColumnDefaultValue('0')]
        public char status
        {
            get { return fstatus; }
            set { SetPropertyValue<char>(nameof(status), ref fstatus, value); }
        }
        char fdel_flag;
        [ColumnDefaultValue('0')]
        public char del_flag
        {
            get { return fdel_flag; }
            set { SetPropertyValue<char>(nameof(del_flag), ref fdel_flag, value); }
        }
        string flogin_ip;
        [Size(50)]
        [ColumnDefaultValue("")]
        public string login_ip
        {
            get { return flogin_ip; }
            set { SetPropertyValue<string>(nameof(login_ip), ref flogin_ip, value); }
        }
        DateTime flogin_date;
        public DateTime login_date
        {
            get { return flogin_date; }
            set { SetPropertyValue<DateTime>(nameof(login_date), ref flogin_date, value); }
        }
        DateTime fpwd_update_date;
        public DateTime pwd_update_date
        {
            get { return fpwd_update_date; }
            set { SetPropertyValue<DateTime>(nameof(pwd_update_date), ref fpwd_update_date, value); }
        }
        string fcreate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string create_by
        {
            get { return fcreate_by; }
            set { SetPropertyValue<string>(nameof(create_by), ref fcreate_by, value); }
        }
        DateTime fcreate_time;
        public DateTime create_time
        {
            get { return fcreate_time; }
            set { SetPropertyValue<DateTime>(nameof(create_time), ref fcreate_time, value); }
        }
        string fupdate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string update_by
        {
            get { return fupdate_by; }
            set { SetPropertyValue<string>(nameof(update_by), ref fupdate_by, value); }
        }
        DateTime fupdate_time;
        public DateTime update_time
        {
            get { return fupdate_time; }
            set { SetPropertyValue<DateTime>(nameof(update_time), ref fupdate_time, value); }
        }
        string fremark;
        [Size(500)]
        public string remark
        {
            get { return fremark; }
            set { SetPropertyValue<string>(nameof(remark), ref fremark, value); }
        }
    }

}
