//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class sys_dict_data : XPLiteObject
    {
        long fdict_code;
        [Key(true)]
        public long dict_code
        {
            get { return fdict_code; }
            set { SetPropertyValue<long>(nameof(dict_code), ref fdict_code, value); }
        }
        int fdict_sort;
        [ColumnDefaultValue(0)]
        public int dict_sort
        {
            get { return fdict_sort; }
            set { SetPropertyValue<int>(nameof(dict_sort), ref fdict_sort, value); }
        }
        string fdict_label;
        [ColumnDefaultValue("")]
        public string dict_label
        {
            get { return fdict_label; }
            set { SetPropertyValue<string>(nameof(dict_label), ref fdict_label, value); }
        }
        string fdict_value;
        [ColumnDefaultValue("")]
        public string dict_value
        {
            get { return fdict_value; }
            set { SetPropertyValue<string>(nameof(dict_value), ref fdict_value, value); }
        }
        string fdict_type;
        [ColumnDefaultValue("")]
        public string dict_type
        {
            get { return fdict_type; }
            set { SetPropertyValue<string>(nameof(dict_type), ref fdict_type, value); }
        }
        string fcss_class;
        public string css_class
        {
            get { return fcss_class; }
            set { SetPropertyValue<string>(nameof(css_class), ref fcss_class, value); }
        }
        string flist_class;
        public string list_class
        {
            get { return flist_class; }
            set { SetPropertyValue<string>(nameof(list_class), ref flist_class, value); }
        }
        char fis_default;
        [ColumnDefaultValue('N')]
        public char is_default
        {
            get { return fis_default; }
            set { SetPropertyValue<char>(nameof(is_default), ref fis_default, value); }
        }
        char fstatus;
        [ColumnDefaultValue('0')]
        public char status
        {
            get { return fstatus; }
            set { SetPropertyValue<char>(nameof(status), ref fstatus, value); }
        }
        string fcreate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string create_by
        {
            get { return fcreate_by; }
            set { SetPropertyValue<string>(nameof(create_by), ref fcreate_by, value); }
        }
        DateTime fcreate_time;
        public DateTime create_time
        {
            get { return fcreate_time; }
            set { SetPropertyValue<DateTime>(nameof(create_time), ref fcreate_time, value); }
        }
        string fupdate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string update_by
        {
            get { return fupdate_by; }
            set { SetPropertyValue<string>(nameof(update_by), ref fupdate_by, value); }
        }
        DateTime fupdate_time;
        public DateTime update_time
        {
            get { return fupdate_time; }
            set { SetPropertyValue<DateTime>(nameof(update_time), ref fupdate_time, value); }
        }
        string fremark;
        [Size(500)]
        public string remark
        {
            get { return fremark; }
            set { SetPropertyValue<string>(nameof(remark), ref fremark, value); }
        }
    }

}
