//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class sys_role : XPLiteObject
    {
        long frole_id;
        [Key(true)]
        public long role_id
        {
            get { return frole_id; }
            set { SetPropertyValue<long>(nameof(role_id), ref frole_id, value); }
        }
        string frole_name;
        [Size(30)]
        public string role_name
        {
            get { return frole_name; }
            set { SetPropertyValue<string>(nameof(role_name), ref frole_name, value); }
        }
        string frole_key;
        public string role_key
        {
            get { return frole_key; }
            set { SetPropertyValue<string>(nameof(role_key), ref frole_key, value); }
        }
        int frole_sort;
        public int role_sort
        {
            get { return frole_sort; }
            set { SetPropertyValue<int>(nameof(role_sort), ref frole_sort, value); }
        }
        char fdata_scope;
        [ColumnDefaultValue('1')]
        public char data_scope
        {
            get { return fdata_scope; }
            set { SetPropertyValue<char>(nameof(data_scope), ref fdata_scope, value); }
        }
        char fstatus;
        public char status
        {
            get { return fstatus; }
            set { SetPropertyValue<char>(nameof(status), ref fstatus, value); }
        }
        char fdel_flag;
        [ColumnDefaultValue('0')]
        public char del_flag
        {
            get { return fdel_flag; }
            set { SetPropertyValue<char>(nameof(del_flag), ref fdel_flag, value); }
        }
        string fcreate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string create_by
        {
            get { return fcreate_by; }
            set { SetPropertyValue<string>(nameof(create_by), ref fcreate_by, value); }
        }
        DateTime fcreate_time;
        public DateTime create_time
        {
            get { return fcreate_time; }
            set { SetPropertyValue<DateTime>(nameof(create_time), ref fcreate_time, value); }
        }
        string fupdate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string update_by
        {
            get { return fupdate_by; }
            set { SetPropertyValue<string>(nameof(update_by), ref fupdate_by, value); }
        }
        DateTime fupdate_time;
        public DateTime update_time
        {
            get { return fupdate_time; }
            set { SetPropertyValue<DateTime>(nameof(update_time), ref fupdate_time, value); }
        }
        string fremark;
        [Size(500)]
        public string remark
        {
            get { return fremark; }
            set { SetPropertyValue<string>(nameof(remark), ref fremark, value); }
        }
    }

}
