//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class sys_job_log : XPLiteObject
    {
        long fjob_log_id;
        [Key(true)]
        public long job_log_id
        {
            get { return fjob_log_id; }
            set { SetPropertyValue<long>(nameof(job_log_id), ref fjob_log_id, value); }
        }
        string fjob_name;
        [Size(64)]
        public string job_name
        {
            get { return fjob_name; }
            set { SetPropertyValue<string>(nameof(job_name), ref fjob_name, value); }
        }
        string fjob_group;
        [Size(64)]
        public string job_group
        {
            get { return fjob_group; }
            set { SetPropertyValue<string>(nameof(job_group), ref fjob_group, value); }
        }
        string finvoke_target;
        [Size(500)]
        public string invoke_target
        {
            get { return finvoke_target; }
            set { SetPropertyValue<string>(nameof(invoke_target), ref finvoke_target, value); }
        }
        string fjob_message;
        [Size(500)]
        public string job_message
        {
            get { return fjob_message; }
            set { SetPropertyValue<string>(nameof(job_message), ref fjob_message, value); }
        }
        char fstatus;
        [ColumnDefaultValue('0')]
        public char status
        {
            get { return fstatus; }
            set { SetPropertyValue<char>(nameof(status), ref fstatus, value); }
        }
        string fexception_info;
        [Size(2000)]
        [ColumnDefaultValue("")]
        public string exception_info
        {
            get { return fexception_info; }
            set { SetPropertyValue<string>(nameof(exception_info), ref fexception_info, value); }
        }
        DateTime fcreate_time;
        public DateTime create_time
        {
            get { return fcreate_time; }
            set { SetPropertyValue<DateTime>(nameof(create_time), ref fcreate_time, value); }
        }
    }

}
