//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class sys_logininfor : XPLiteObject
    {
        long finfo_id;
        [Key(true)]
        public long info_id
        {
            get { return finfo_id; }
            set { SetPropertyValue<long>(nameof(info_id), ref finfo_id, value); }
        }
        string flogin_name;
        [Size(50)]
        [ColumnDefaultValue("")]
        public string login_name
        {
            get { return flogin_name; }
            set { SetPropertyValue<string>(nameof(login_name), ref flogin_name, value); }
        }
        string fipaddr;
        [Size(50)]
        [ColumnDefaultValue("")]
        public string ipaddr
        {
            get { return fipaddr; }
            set { SetPropertyValue<string>(nameof(ipaddr), ref fipaddr, value); }
        }
        string flogin_location;
        [Size(255)]
        [ColumnDefaultValue("")]
        public string login_location
        {
            get { return flogin_location; }
            set { SetPropertyValue<string>(nameof(login_location), ref flogin_location, value); }
        }
        string fbrowser;
        [Size(50)]
        [ColumnDefaultValue("")]
        public string browser
        {
            get { return fbrowser; }
            set { SetPropertyValue<string>(nameof(browser), ref fbrowser, value); }
        }
        string fos;
        [Size(50)]
        [ColumnDefaultValue("")]
        public string os
        {
            get { return fos; }
            set { SetPropertyValue<string>(nameof(os), ref fos, value); }
        }
        char fstatus;
        [ColumnDefaultValue('0')]
        public char status
        {
            get { return fstatus; }
            set { SetPropertyValue<char>(nameof(status), ref fstatus, value); }
        }
        string fmsg;
        [Size(255)]
        [ColumnDefaultValue("")]
        public string msg
        {
            get { return fmsg; }
            set { SetPropertyValue<string>(nameof(msg), ref fmsg, value); }
        }
        DateTime flogin_time;
        public DateTime login_time
        {
            get { return flogin_time; }
            set { SetPropertyValue<DateTime>(nameof(login_time), ref flogin_time, value); }
        }
    }

}
