//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class sys_post : XPLiteObject
    {
        long fpost_id;
        [Key(true)]
        public long post_id
        {
            get { return fpost_id; }
            set { SetPropertyValue<long>(nameof(post_id), ref fpost_id, value); }
        }
        string fpost_code;
        [Size(64)]
        public string post_code
        {
            get { return fpost_code; }
            set { SetPropertyValue<string>(nameof(post_code), ref fpost_code, value); }
        }
        string fpost_name;
        [Size(50)]
        public string post_name
        {
            get { return fpost_name; }
            set { SetPropertyValue<string>(nameof(post_name), ref fpost_name, value); }
        }
        int fpost_sort;
        public int post_sort
        {
            get { return fpost_sort; }
            set { SetPropertyValue<int>(nameof(post_sort), ref fpost_sort, value); }
        }
        char fstatus;
        public char status
        {
            get { return fstatus; }
            set { SetPropertyValue<char>(nameof(status), ref fstatus, value); }
        }
        string fcreate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string create_by
        {
            get { return fcreate_by; }
            set { SetPropertyValue<string>(nameof(create_by), ref fcreate_by, value); }
        }
        DateTime fcreate_time;
        public DateTime create_time
        {
            get { return fcreate_time; }
            set { SetPropertyValue<DateTime>(nameof(create_time), ref fcreate_time, value); }
        }
        string fupdate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string update_by
        {
            get { return fupdate_by; }
            set { SetPropertyValue<string>(nameof(update_by), ref fupdate_by, value); }
        }
        DateTime fupdate_time;
        public DateTime update_time
        {
            get { return fupdate_time; }
            set { SetPropertyValue<DateTime>(nameof(update_time), ref fupdate_time, value); }
        }
        string fremark;
        [Size(500)]
        public string remark
        {
            get { return fremark; }
            set { SetPropertyValue<string>(nameof(remark), ref fremark, value); }
        }
    }

}
