//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class sys_job : XPLiteObject
    {
        string finvoke_target;
        [Size(500)]
        public string invoke_target
        {
            get { return finvoke_target; }
            set { SetPropertyValue<string>(nameof(invoke_target), ref finvoke_target, value); }
        }
        string fcron_expression;
        [Size(255)]
        [ColumnDefaultValue("")]
        public string cron_expression
        {
            get { return fcron_expression; }
            set { SetPropertyValue<string>(nameof(cron_expression), ref fcron_expression, value); }
        }
        string fmisfire_policy;
        [Size(20)]
        [ColumnDefaultValue("3")]
        public string misfire_policy
        {
            get { return fmisfire_policy; }
            set { SetPropertyValue<string>(nameof(misfire_policy), ref fmisfire_policy, value); }
        }
        char fconcurrent;
        [ColumnDefaultValue('1')]
        public char concurrent
        {
            get { return fconcurrent; }
            set { SetPropertyValue<char>(nameof(concurrent), ref fconcurrent, value); }
        }
        char fstatus;
        [ColumnDefaultValue('0')]
        public char status
        {
            get { return fstatus; }
            set { SetPropertyValue<char>(nameof(status), ref fstatus, value); }
        }
        string fcreate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string create_by
        {
            get { return fcreate_by; }
            set { SetPropertyValue<string>(nameof(create_by), ref fcreate_by, value); }
        }
        DateTime fcreate_time;
        public DateTime create_time
        {
            get { return fcreate_time; }
            set { SetPropertyValue<DateTime>(nameof(create_time), ref fcreate_time, value); }
        }
        string fupdate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string update_by
        {
            get { return fupdate_by; }
            set { SetPropertyValue<string>(nameof(update_by), ref fupdate_by, value); }
        }
        DateTime fupdate_time;
        public DateTime update_time
        {
            get { return fupdate_time; }
            set { SetPropertyValue<DateTime>(nameof(update_time), ref fupdate_time, value); }
        }
        string fremark;
        [Size(500)]
        [ColumnDefaultValue("")]
        public string remark
        {
            get { return fremark; }
            set { SetPropertyValue<string>(nameof(remark), ref fremark, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("job_id")]
            public long job_id { get; set; }
            [Size(64)]
            [Persistent("job_name")]
            public string job_name { get; set; }
            [Size(64)]
            [Persistent("job_group")]
            public string job_group { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
