//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class sys_dept : XPLiteObject
    {
        long fdept_id;
        [Key(true)]
        public long dept_id
        {
            get { return fdept_id; }
            set { SetPropertyValue<long>(nameof(dept_id), ref fdept_id, value); }
        }
        long fparent_id;
        [ColumnDefaultValue(0)]
        public long parent_id
        {
            get { return fparent_id; }
            set { SetPropertyValue<long>(nameof(parent_id), ref fparent_id, value); }
        }
        string fancestors;
        [Size(50)]
        [ColumnDefaultValue("")]
        public string ancestors
        {
            get { return fancestors; }
            set { SetPropertyValue<string>(nameof(ancestors), ref fancestors, value); }
        }
        string fdept_name;
        [Size(30)]
        [ColumnDefaultValue("")]
        public string dept_name
        {
            get { return fdept_name; }
            set { SetPropertyValue<string>(nameof(dept_name), ref fdept_name, value); }
        }
        int forder_num;
        [ColumnDefaultValue(0)]
        public int order_num
        {
            get { return forder_num; }
            set { SetPropertyValue<int>(nameof(order_num), ref forder_num, value); }
        }
        string fleader;
        [Size(20)]
        public string leader
        {
            get { return fleader; }
            set { SetPropertyValue<string>(nameof(leader), ref fleader, value); }
        }
        string fphone;
        [Size(11)]
        public string phone
        {
            get { return fphone; }
            set { SetPropertyValue<string>(nameof(phone), ref fphone, value); }
        }
        string femail;
        [Size(50)]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        char fstatus;
        [ColumnDefaultValue('0')]
        public char status
        {
            get { return fstatus; }
            set { SetPropertyValue<char>(nameof(status), ref fstatus, value); }
        }
        char fdel_flag;
        [ColumnDefaultValue('0')]
        public char del_flag
        {
            get { return fdel_flag; }
            set { SetPropertyValue<char>(nameof(del_flag), ref fdel_flag, value); }
        }
        string fcreate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string create_by
        {
            get { return fcreate_by; }
            set { SetPropertyValue<string>(nameof(create_by), ref fcreate_by, value); }
        }
        DateTime fcreate_time;
        public DateTime create_time
        {
            get { return fcreate_time; }
            set { SetPropertyValue<DateTime>(nameof(create_time), ref fcreate_time, value); }
        }
        string fupdate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string update_by
        {
            get { return fupdate_by; }
            set { SetPropertyValue<string>(nameof(update_by), ref fupdate_by, value); }
        }
        DateTime fupdate_time;
        public DateTime update_time
        {
            get { return fupdate_time; }
            set { SetPropertyValue<DateTime>(nameof(update_time), ref fupdate_time, value); }
        }
    }

}
