//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TestRestClient.ruoyi
{

    public partial class sys_dict_type : XPLiteObject
    {
        long fdict_id;
        [Key(true)]
        public long dict_id
        {
            get { return fdict_id; }
            set { SetPropertyValue<long>(nameof(dict_id), ref fdict_id, value); }
        }
        string fdict_name;
        [ColumnDefaultValue("")]
        public string dict_name
        {
            get { return fdict_name; }
            set { SetPropertyValue<string>(nameof(dict_name), ref fdict_name, value); }
        }
        string fdict_type;
        [Indexed(Name = @"dict_type", Unique = true)]
        [ColumnDefaultValue("")]
        public string dict_type
        {
            get { return fdict_type; }
            set { SetPropertyValue<string>(nameof(dict_type), ref fdict_type, value); }
        }
        char fstatus;
        [ColumnDefaultValue('0')]
        public char status
        {
            get { return fstatus; }
            set { SetPropertyValue<char>(nameof(status), ref fstatus, value); }
        }
        string fcreate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string create_by
        {
            get { return fcreate_by; }
            set { SetPropertyValue<string>(nameof(create_by), ref fcreate_by, value); }
        }
        DateTime fcreate_time;
        public DateTime create_time
        {
            get { return fcreate_time; }
            set { SetPropertyValue<DateTime>(nameof(create_time), ref fcreate_time, value); }
        }
        string fupdate_by;
        [Size(64)]
        [ColumnDefaultValue("")]
        public string update_by
        {
            get { return fupdate_by; }
            set { SetPropertyValue<string>(nameof(update_by), ref fupdate_by, value); }
        }
        DateTime fupdate_time;
        public DateTime update_time
        {
            get { return fupdate_time; }
            set { SetPropertyValue<DateTime>(nameof(update_time), ref fupdate_time, value); }
        }
        string fremark;
        [Size(500)]
        public string remark
        {
            get { return fremark; }
            set { SetPropertyValue<string>(nameof(remark), ref fremark, value); }
        }
    }

}
